NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/doc"

api_authenticate_check:
    path: /api/authenticate

api:
    type: rest
    prefix: "/api"
    resource: "routing_api.yml"

api_micro_service:
    type: annotation
    resource : "@AppBundle/Controller/MicroServiceController.php"